//import CreateDocument from "@/components/CreateDocument";
import type { Metadata } from "next";
import DocumentList from "@/components/documents/DocumentList";
import ProtectedContent from "@/components/ProtectedContent";
//import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { createServerComponentClient } from "@supabase/auth-helpers-nextjs";
import { cookies } from "next/headers";
//import Image from "next/image";
import { TypographyH1, TypographyLead } from "@/components/ui/typography";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import Link from "next/link";
import DocumentSearchInput from "@/components/documents/DocumentSearchInput";
import ProjectsTable from "@/components/projects/ProjectsTable";

export const metadata: Metadata = {
  title: "Projects",
  description: "Generated by create next app",
};

export default async function ProjectsPage({
  searchParams,
}: {
  searchParams: { [key: string]: string | string[] | undefined };
}) {
  const supabase = createServerComponentClient({ cookies });

  // text search
  const query = searchParams?.query || "";

  // db call
  const { data: goals, count } = await supabase
    .from("goals")
    .select("*", { count: "exact" });
  // .range(start, finish);

  return (
    <>
      <ProtectedContent>
        <div className="container">
          <div className="mb-8">
            <div className="flex mb-2 items-center justify-between">
              <TypographyH1>
                Projects 
              </TypographyH1>
            </div>

            <TypographyLead>
              Lorem, ipsum dolor sit amet consectetur adipisicing elit. Placeat,
              sit.
            </TypographyLead>
          </div>
          {goals ? (
            <ProjectsTable projects={goals} />
          ) : (
            <div>
              No goals yet! <br />
              make one!
            </div>
          )}

        </div>
      </ProtectedContent>
    </>
  );
}
