import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { cookies, headers } from "next/headers";
import { ThemeProvider } from "@/components/ThemeProvider";
import NextTopLoader from 'nextjs-toploader';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "SOW Generator",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: // footerContent,
{
  children: React.ReactNode;
  // footerContent?: React.ReactNode;
}) {
  // theme stuff
  const cookieStore = cookies();
  const theme = cookieStore.get("theme");

  // pathname stuff
  const headersList = headers();
  const header_url = headersList.get("x-url") || "";

  return (
    <html lang="en" data-theme={theme?.value}>
      <body className={inter.className + ' overflow-x-hidden'}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <NextTopLoader />
          <div className="w-screen h-screen flex flex-col justify-between">
            <div>
              <Navbar />
              <main className="overflow-y-auto">{children}</main>
            </div>
            <Footer />
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
